### ISSUE TITLE
Some problems using a controller pad.

### ISSUE THREAD

**Issue by Cal-Draven** [PoisDesu/Didnapper-2#61]
**Bug description**
Sometimes the pad does not respond navigating on the menu. To fix that usually I press with the keyboard one key and then the pad works again. I have not suffered this problem during the game walking on the map and during the battles. I found this just navigating in the menus. 

**To reproduce**
Just play the game.

**Expected behavior**
N/A

**Screenshots/Video**
N/A

**Environment (please complete the following information):**
-  OS & Version: macOS 10.5 Catalina
-  Game version and platform: 1.0.3 Itch 

**Input method**
Pad controller 8Bitdo SF30 Pro.

**Error logs**
N/A

**Save file**
N/A

**Additional context**
N/A

**Comment by AbruptLee** [comment]
Have same exact issue on Windows 10 with a PS4 controller connected by USB cable.

**Comment by PoisDesu** [comment]
Are you both using XInput?

**Comment by AbruptLee** [comment]
No, only game running with controller plugged in. I believe I've had same issue happen with battle menu unlike Cal. Though the issue happens most in pause menu, and is easily but annoyingly fixed by pressing an arrow key on keyboard. 

More specifics on issue is while using D-pad of a controller sometimes the cursor will be stuck on a selection whether you press up or down. You will see hear sound effect but cursor may blink but still stays on current selection. Pressing keyboard arrow frees cursor and controller works fine. Issue may randomly occur on same play session.

**Comment by PoisDesu** [comment]
Could you try interfacing your controller with XInput from now on and tell me if it still happens?

**Comment by AbruptLee** [comment]
Downloaded and installed https://github.com/Ryochan7/DS4Windows ; and am now able to play by bluetooth while before was USB connection directly. This issue still randomly appears with this setup but it seems to only appear in the Skills, Equip, and Status submenus. Arrow key on keyboard still fixes issue.
